image: openjdk:17

stages:
  - build
  - test
  - package

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

build-job:
  stage: build
  script:
    - ./gradlew build

test-job:
  stage: test
  script:
    - ./gradlew test

package-job:
  stage: package
  script:
    - ./gradlew bootJar
    - mv build/libs/*.jar demo.jar
