package com.example.cligenerator.model;

import java.util.ArrayList;
import java.util.List;

/**
 * Model class to hold additional service methods generated by AI
 */
public class ServiceMethodDefinition {
    private String entityName;
    private List<String> additionalMethods;
    private String rawMethodCode;

    public ServiceMethodDefinition() {
        this.additionalMethods = new ArrayList<>();
    }

    public ServiceMethodDefinition(String entityName, String rawMethodCode) {
        this.entityName = entityName;
        this.rawMethodCode = rawMethodCode;
        this.additionalMethods = new ArrayList<>();
    }

    public String getEntityName() {
        return entityName;
    }

    public void setEntityName(String entityName) {
        this.entityName = entityName;
    }

    public List<String> getAdditionalMethods() {
        return additionalMethods;
    }

    public void setAdditionalMethods(List<String> additionalMethods) {
        this.additionalMethods = additionalMethods;
    }

    public void addMethod(String method) {
        this.additionalMethods.add(method);
    }

    public String getRawMethodCode() {
        return rawMethodCode;
    }

    public void setRawMethodCode(String rawMethodCode) {
        this.rawMethodCode = rawMethodCode;
    }

    public boolean hasAdditionalMethods() {
        return rawMethodCode != null && !rawMethodCode.trim().isEmpty();
    }
}
